[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/src/main.js"
preDeployCommand = "chmod +x ./railway/init-app.sh && ./railway/init-app.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
